# ══════════════════════════════════════════════════════════════════════════════
# MulBrandEval — Phase 1C: Component Validation Script
# ══════════════════════════════════════════════════════════════════════════════
#
# Purpose:
#   Validates that each DAG node tool (GPT-4o mini VQA, EasyOCR) is capable
#   of measuring its target compliance dimension reliably, BEFORE running the
#   full multilingual evaluation in Phase 2A. This is a tool-calibration step,
#   not an evaluation of generated images.
#
# Nodes (in execution order):
#   Node 1 — Object Presence    GPT-4o mini VQA   MS-COCO val2017       F1 >= 0.80
#   Node 2 — Spatial Layout     GPT-4o mini VQA   PaintSkills spatial    Acc >= 0.50
#   Node 3 — Attribute/Colour   BLIP-VQA + mCLIP  T2I-CompBench color    rho >= 0.60  [FAILED — kept as audit trail]
#   Node 3r— Attribute/Colour   GPT-4o mini VQA   T2I-CompBench color    rho >= 0.60  [recalibrated]
#   Node 4 — Typography         EasyOCR 1.7.1     DrawBench Text         Acc >= 0.75
#
# Usage:
#   python phase1c_agent_validation/phase1c_validate.py 1    -> Node 1 only
#   python phase1c_agent_validation/phase1c_validate.py 2    -> Node 2 only
#   python phase1c_agent_validation/phase1c_validate.py 3    -> Node 3 original (mCLIP, audit trail)
#   python phase1c_agent_validation/phase1c_validate.py 3r   -> Node 3 recalibrated (GPT-4o mini)
#   python phase1c_agent_validation/phase1c_validate.py 4    -> Node 4 only
#   python phase1c_agent_validation/phase1c_validate.py      -> all nodes in sequence
#
# Notes:
#   - Run '3' before '3r': recalibrated Node 3 needs BLIP scores from the
#     original run as its reference signal.
#   - Node 3 images must be pre-generated by phase1c_generate.py before
#     running nodes 3 or 3r.
#   - Node 2 downloads PaintSkills images on first run; they are cached
#     locally to data/reference_images/paintskills_node2/ on subsequent runs.
#   - All results accumulate in results/phase1c/ — individual node CSVs,
#     component_validation_table.csv, and phase1c_summary.txt.
#
# Author: MulBrandEval project
# ══════════════════════════════════════════════════════════════════════════════

import os
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"   # suppress OpenMP duplicate-lib warning on Windows

import json
import re
import random
import base64
import time
import csv
import sys
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv
from openai import OpenAI

# ── Environment ────────────────────────────────────────────────────────────────
load_dotenv()
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

# Fixed seed used throughout: image sampling, negative sampling, scene sampling.
# Changed from seed 123 to 42 in Phase 1B per professor meeting (cost reduction).
SEED = 42
random.seed(SEED)

# ── Paths ──────────────────────────────────────────────────────────────────────
# Input data — reference images and annotations
COCO_IMAGES_DIR       = Path("data/reference_images/coco_phase1a")   # 50 COCO val2017 JPEGs
COCO_ANNOTATIONS      = Path("annotations/instances_val2017.json")   # COCO ground truth
PROMPTS_CSV           = Path("data/prompts/en/coco_prompts_en.csv")  # 50 sampled COCO prompts (Phase 1A)
PAINTSKILLS_CACHE_DIR = Path("data/reference_images/paintskills_node2")  # PaintSkills PNGs (downloaded on first run)

# Input data — generated images used in Phase 1B/1C
PHASE1B_IMAGES_DIR    = Path("data/generated_images/phase1b")        # Phase 1B images (Node 4 uses these)
PHASE1B_PROMPTS_EN    = Path("data/prompts/en/phase1b_prompts_en.csv")
NODE3_IMAGES_DIR      = Path("data/generated_images/phase1c/node3")  # Node 3 generated images
NODE3_PROMPTS_CSV     = Path("data/prompts/en/phase1c_node3_prompts_en.csv")  # 30 T2I-CompBench color_val prompts

# Output paths — all results land in results/phase1c/
RESULTS_DIR       = Path("results/phase1c")
NODE1_CSV         = RESULTS_DIR / "node1_object_presence.csv"
NODE2_CSV         = RESULTS_DIR / "node2_spatial_layout.csv"
NODE3_CSV         = RESULTS_DIR / "node3_colour_attribute.csv"      # original mCLIP run
NODE3_RECALIB_CSV = RESULTS_DIR / "node3_recalibrated.csv"          # GPT-4o mini recalibration
NODE4_CSV         = RESULTS_DIR / "node4_typography.csv"
VALIDATION_TABLE  = RESULTS_DIR / "component_validation_table.csv"  # master summary table
SUMMARY_TXT       = RESULTS_DIR / "phase1c_summary.txt"             # human-readable one-liner per node

RESULTS_DIR.mkdir(parents=True, exist_ok=True)


# ══════════════════════════════════════════════════════════════════════════════
# NODE 1 — Object Presence Validation
#
# Goal:   Confirm GPT-4o mini VQA can reliably detect whether a named object
#         is present or absent in an image — the binary signal used in Phase 2A
#         to score object compliance.
#
# Method: For each of 50 MS-COCO val2017 images, query GPT-4o mini with
#         balanced positive (objects present) and negative (objects absent)
#         yes/no questions. Compare predictions to COCO ground truth.
#
# Dataset: MS-COCO val2017, 50 images sampled in Phase 1A (seed 42).
#          Ground truth from instances_val2017.json (80 categories).
#
# Metric:  F1 score across all (image, object) pairs.
# Target:  F1 >= 0.80
# ══════════════════════════════════════════════════════════════════════════════

def run_node1():
    print("=" * 65)
    print("NODE 1 — Object Presence Validation")
    print("=" * 65)

    # ── Load COCO ground truth ────────────────────────────────────────────────
    print("\nLoading COCO annotations...")
    with open(COCO_ANNOTATIONS, "r", encoding="utf-8") as f:
        coco = json.load(f)

    # Map category_id → category_name for all 80 COCO classes
    category_map       = {cat["id"]: cat["name"] for cat in coco["categories"]}
    all_category_names = set(category_map.values())
    print(f"  COCO categories loaded: {len(all_category_names)}")

    # Load the 50 image IDs we sampled in Phase 1A
    prompts_df    = pd.read_csv(PROMPTS_CSV)
    our_image_ids = set(prompts_df["image_id"].tolist())
    print(f"  Prompt image IDs loaded: {len(our_image_ids)}")

    # Build per-image set of present categories from COCO annotations
    print("  Building per-image ground truth...")
    image_categories = {iid: set() for iid in our_image_ids}
    for ann in coco["annotations"]:
        iid = ann["image_id"]
        if iid in our_image_ids:
            image_categories[iid].add(category_map[ann["category_id"]])

    present_counts = [len(v) for v in image_categories.values()]
    print(f"  Avg objects per image: {sum(present_counts)/len(present_counts):.1f}  "
          f"(min {min(present_counts)}, max {max(present_counts)})")

    # ── GPT-4o mini VQA helpers ───────────────────────────────────────────────
    def encode_image(path: Path) -> str:
        """Read an image file and return a base64-encoded string."""
        with open(path, "rb") as f:
            return base64.b64encode(f.read()).decode("utf-8")

    def query_object_present(image_path: Path, object_name: str, retries: int = 3) -> int:
        """
        Ask GPT-4o mini: 'Is a [object_name] clearly visible in this image?'
        Returns 1 (yes) or 0 (no). Uses detail=low for cost efficiency.
        Retries up to 3 times on API errors before returning 0.
        """
        b64 = encode_image(image_path)
        for attempt in range(retries):
            try:
                response = client.chat.completions.create(
                    model="gpt-4o-mini",
                    messages=[{
                        "role": "user",
                        "content": [
                            {"type": "image_url",
                             "image_url": {"url": f"data:image/jpeg;base64,{b64}",
                                           "detail": "low"}},
                            {"type": "text",
                             "text": (f"Is a {object_name} clearly visible in this image? "
                                      "Answer with only 'yes' or 'no'.")}
                        ]
                    }],
                    max_tokens=5,
                    temperature=0   # greedy decoding; minimises but does not guarantee cross-run determinism
                )
                answer = response.choices[0].message.content.strip().lower()
                return 1 if answer.startswith("yes") else 0
            except Exception as e:
                print(f"    Retry {attempt + 1}/3 ({object_name}): {e}")
                time.sleep(3)
        return 0   # conservative default on persistent failure

    # ── Run balanced VQA queries ──────────────────────────────────────────────
    results       = []
    total_queries = 0

    print(f"\nRunning VQA queries across {len(prompts_df)} images...")
    print("  (This will take several minutes due to API rate limiting)\n")

    for idx, row in prompts_df.iterrows():
        image_id       = row["image_id"]
        image_filename = f"{image_id:012d}.jpg"   # COCO zero-padded 12-digit filename
        image_path     = COCO_IMAGES_DIR / image_filename

        if not image_path.exists():
            print(f"  [WARNING] Image not found: {image_filename} — skipping")
            continue

        # Positive cases: objects actually present in this image (GT = 1)
        present   = list(image_categories[image_id])
        # Negative cases: objects definitely absent — sample same count as positives
        # to keep the evaluation balanced (equal pos/neg prevents accuracy inflation)
        absent    = sorted(all_category_names - image_categories[image_id])
        random.shuffle(absent)
        negatives = absent[:len(present)]

        test_cases     = [(obj, 1) for obj in present] + [(obj, 0) for obj in negatives]
        total_queries += len(test_cases)

        print(f"  [{idx + 1:2d}/50] image_id={image_id} | "
              f"+{len(present)} pos  -{len(negatives)} neg  ({len(test_cases)} queries)")

        for object_name, ground_truth in test_cases:
            prediction = query_object_present(image_path, object_name)
            results.append({
                "image_id":     image_id,
                "object_name":  object_name,
                "ground_truth": ground_truth,
                "prediction":   prediction,
                "correct":      int(prediction == ground_truth)
            })
            time.sleep(0.4)   # stay within GPT-4o mini rate limits

    # ── Save per-prediction results ───────────────────────────────────────────
    results_df = pd.DataFrame(results)
    results_df.to_csv(NODE1_CSV, index=False, encoding="utf-8")
    print(f"\nDetailed results saved: {NODE1_CSV}  ({len(results_df)} rows)")

    # ── Compute precision / recall / F1 ──────────────────────────────────────
    tp = len(results_df[(results_df["ground_truth"] == 1) & (results_df["prediction"] == 1)])
    fp = len(results_df[(results_df["ground_truth"] == 0) & (results_df["prediction"] == 1)])
    fn = len(results_df[(results_df["ground_truth"] == 1) & (results_df["prediction"] == 0)])
    tn = len(results_df[(results_df["ground_truth"] == 0) & (results_df["prediction"] == 0)])

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall    = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1        = (2 * precision * recall / (precision + recall)
                 if (precision + recall) > 0 else 0.0)

    TARGET    = 0.80
    pass_fail = "PASS" if f1 >= TARGET else "FAIL"
    threshold = "GPT-4o mini VQA | 'Is a [object] clearly visible?' binary yes/no | detail=low | temperature=0"

    print("\n" + "-" * 45)
    print(f"  Total queries : {total_queries}")
    print(f"  TP={tp}  FP={fp}  FN={fn}  TN={tn}")
    print(f"  Precision     : {precision:.4f}")
    print(f"  Recall        : {recall:.4f}")
    print(f"  F1            : {f1:.4f}  (target >= {TARGET})")
    print(f"  Status        : {pass_fail}")
    print("-" * 45)

    if pass_fail == "FAIL":
        print("\n  NOTE: F1 below target. Consider adjusting the VQA prompt")
        print("  or lowering the detection threshold before Phase 2A.")

    # ── Update component validation table ────────────────────────────────────
    table_row = {
        "node":                 "Node 1",
        "capability":           "Object Presence",
        "tool":                 "GPT-4o mini VQA",
        "dataset":              "MS-COCO val2017 (n=50 images)",
        "metric":               "F1",
        "score":                round(f1, 4),
        "target":               f">= {TARGET}",
        "pass_fail":            pass_fail,
        "evaluation_method": threshold
    }
    write_header = not VALIDATION_TABLE.exists()
    with open(VALIDATION_TABLE, "a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(table_row.keys()))
        if write_header:
            writer.writeheader()
        writer.writerow(table_row)
    print(f"\nComponent validation table updated: {VALIDATION_TABLE}")

    # ── Append one-liner to summary txt ──────────────────────────────────────
    node1_summary = (
        f"Node 1 | Object Presence | GPT-4o mini VQA | "
        f"F1={f1:.4f} | target>=0.80 | {pass_fail} | "
        f"P={precision:.4f} R={recall:.4f} | "
        f"TP={tp} FP={fp} FN={fn} TN={tn}\n"
    )
    with open(SUMMARY_TXT, "a", encoding="utf-8") as f:
        f.write("MulBrandEval Phase 1C - Component Validation Summary\n")
        f.write("=" * 60 + "\n")
        f.write(node1_summary)

    print(f"Summary written: {SUMMARY_TXT}")
    print("\nNode 1 validation complete.")
    return f1, pass_fail


# ══════════════════════════════════════════════════════════════════════════════
# NODE 2 — Spatial Layout Validation
#
# Goal:   Confirm GPT-4o mini VQA can correctly identify spatial relations
#         between objects (left/right/front/behind), the signal used in
#         Phase 2A to score spatial compliance.
#
# Method: Sample 30 scenes from PaintSkills spatial_val split (seed 42).
#         For each scene, ask GPT-4o mini two balanced yes/no questions:
#           - Positive: Is [obj1] to the [correct direction] of [obj0]?  (GT = YES)
#           - Negative: Is [obj1] to the [opposite direction] of [obj0]? (GT = NO)
#         This balanced design prevents always-yes / always-no bias.
#
# Dataset: j-min/PaintSkills on HuggingFace, spatial_val split (2700 entries).
#          Images are 720×720 synthetic PNG renders. Downloaded and cached
#          locally on first run.
#
# Dataset structure:
#   scenes['data'][i]['id']              -> 'spatial_val_00042'
#   scenes['data'][i]['text']            -> 'a dog is left to a car'
#   scenes['data'][i]['objects'][0]      -> reference object  (relation = None)
#   scenes['data'][i]['objects'][1]      -> positioned object (relation = 'left_0')
#   image filename                       -> image_spatial_val_00042.png
#
# Metric:  Spatial relation accuracy across all 60 binary queries.
# Target:  Accuracy >= 0.50 (better than random chance for left/right)
#
# Note on metric change: The exposé specified IoU vs DETR bounding boxes.
# Since Phase 1C uses GPT-4o mini VQA throughout (no bbox detector available),
# spatial relation accuracy replaces IoU. The threshold (>= 0.50) is preserved.
# This deviation is documented in the component validation table.
# ══════════════════════════════════════════════════════════════════════════════

def run_node2():
    from huggingface_hub import hf_hub_download
    import shutil

    print("=" * 65)
    print("NODE 2 — Spatial Layout Validation")
    print("=" * 65)

    # ── Load PaintSkills scenes JSON ──────────────────────────────────────────
    # The JSON has a single top-level key 'data' containing a list of 2700 dicts.
    # Each dict has: id, text, scene, skill, split, objects[]
    print("\n  Loading PaintSkills spatial_val.json from HuggingFace...")
    scenes_path = hf_hub_download(
        'j-min/PaintSkills',
        'spatial/scenes/spatial_val.json',
        repo_type='dataset'
    )
    with open(scenes_path, 'r', encoding='utf-8') as f:
        scenes_json = json.load(f)

    scenes = scenes_json['data']
    print(f"  Total scenes loaded: {len(scenes)}")

    # ── Sample 30 scenes (seed 42) ────────────────────────────────────────────
    # Use a local Random instance (not the global one) so this sampling
    # is reproducible and independent of call order in the 'all' run.
    N_SAMPLE = 30
    rng      = random.Random(SEED)
    sampled  = rng.sample(scenes, N_SAMPLE)
    print(f"  Sampled {N_SAMPLE} scenes with seed {SEED}")
    print("  Sample IDs (first 5):", [s['id'] for s in sampled[:5]], "...")

    # ── Opposite-direction lookup ─────────────────────────────────────────────
    # Used to construct the negative (wrong-direction) question for each scene.
    OPPOSITE = {
        'left':   'right',
        'right':  'left',
        'above':  'below',   # added: PaintSkills spatial_val includes above/below relations
        'below':  'above',   # added: confirmed from node2 run (12/30 scenes were above/below)
        'front':  'behind',
        'behind': 'front',
    }

    # ── Local image cache ─────────────────────────────────────────────────────
    # Images are downloaded from HuggingFace and cached locally so that
    # re-runs (e.g. retries after a GPT error) do not re-download.
    PAINTSKILLS_CACHE_DIR.mkdir(parents=True, exist_ok=True)

    def get_image(scene_id: str) -> Path:
        """
        Return local path to a PaintSkills image, downloading from HuggingFace
        if not already cached.
        scene_id example: 'spatial_val_00042'
        filename example: 'image_spatial_val_00042.png'
        """
        filename   = f"image_{scene_id}.png"
        local_path = PAINTSKILLS_CACHE_DIR / filename
        if not local_path.exists():
            hf_path    = f"spatial/val_images/{filename}"
            downloaded = hf_hub_download(
                'j-min/PaintSkills', hf_path, repo_type='dataset'
            )
            shutil.copy(downloaded, local_path)
        return local_path

    def query_spatial(image_path: Path, obj0: str, obj1: str,
                      direction: str, retries: int = 3) -> int:
        """
        Ask GPT-4o mini: 'Is the [obj1] to the [direction] of the [obj0]?'
        Returns 1 (yes) or 0 (no). Uses detail=low for cost and consistency
        with Node 1 / Node 3r. Retries up to 3 times on API errors.
        """
        with open(image_path, "rb") as f:
            b64 = base64.b64encode(f.read()).decode("utf-8")

        question = (
            f"In this image, is the {obj1} positioned to the {direction} "
            f"of the {obj0}? Answer with only 'yes' or 'no'."
        )

        for attempt in range(retries):
            try:
                response = client.chat.completions.create(
                    model="gpt-4o-mini",
                    messages=[{
                        "role": "user",
                        "content": [
                            {"type": "image_url",
                             "image_url": {
                                 "url": f"data:image/png;base64,{b64}",
                                 "detail": "low"
                             }},
                            {"type": "text", "text": question}
                        ]
                    }],
                    max_tokens=5,
                    temperature=0
                )
                answer = response.choices[0].message.content.strip().lower()
                return 1 if answer.startswith("yes") else 0
            except Exception as e:
                print(f"    Retry {attempt + 1}/3 ({direction}): {e}")
                time.sleep(3)
        return 0   # conservative default on persistent failure

    # ── Run balanced spatial VQA ──────────────────────────────────────────────
    results       = []
    total_correct = 0
    total_queries = 0

    print(f"\n  Running VQA: {N_SAMPLE} scenes × 2 questions = {N_SAMPLE * 2} GPT-4o mini calls")
    print("  (detail=low; ~$0.003 estimated cost)\n")

    for i, scene in enumerate(sampled):
        scene_id     = scene['id']                          # e.g. 'spatial_val_00042'
        text         = scene['text']                        # e.g. 'a dog is left to a car'
        obj0         = scene['objects'][0]['coconame']      # reference object (relation=None)
        obj1         = scene['objects'][1]['coconame']      # positioned object (has relation)
        relation_raw = scene['objects'][1]['relation']      # e.g. 'left_0'
        direction    = relation_raw.split('_')[0]          # e.g. 'left'
        opposite     = OPPOSITE.get(direction, 'right')    # e.g. 'right'

        # Download image, cached after first run
        try:
            img_path = get_image(scene_id)
        except Exception as e:
            print(f"  [{i + 1:2d}/{N_SAMPLE}] DOWNLOAD FAILED {scene_id}: {e} — skipping")
            continue

        # Positive question: correct direction — ground truth = YES (expect pred=1)
        pred_pos = query_spatial(img_path, obj0, obj1, direction)
        corr_pos = int(pred_pos == 1)
        time.sleep(0.4)

        # Negative question: opposite direction — ground truth = NO (expect pred=0)
        pred_neg = query_spatial(img_path, obj0, obj1, opposite)
        corr_neg = int(pred_neg == 0)
        time.sleep(0.4)

        total_correct += corr_pos + corr_neg
        total_queries += 2

        print(f"  [{i + 1:2d}/{N_SAMPLE}] {scene_id} | "
              f"'{obj1} {direction} {obj0}' | "
              f"pos={'HIT' if corr_pos else 'MISS'}  "
              f"neg={'HIT' if corr_neg else 'MISS'}")

        results.append({
            "scene_id":         scene_id,
            "text":             text,
            "obj0":             obj0,
            "obj1":             obj1,
            "direction":        direction,
            "opposite":         opposite,
            "pred_positive":    pred_pos,    # 1=yes, 0=no (GT should be 1)
            "pred_negative":    pred_neg,    # 1=yes, 0=no (GT should be 0)
            "correct_positive": corr_pos,
            "correct_negative": corr_neg,
        })

    # ── Save per-scene results ────────────────────────────────────────────────
    results_df = pd.DataFrame(results)
    results_df.to_csv(NODE2_CSV, index=False, encoding='utf-8')
    print(f"\n  Detailed results saved: {NODE2_CSV}  ({len(results_df)} rows)")

    # ── Compute accuracy ──────────────────────────────────────────────────────
    accuracy  = total_correct / total_queries if total_queries > 0 else 0.0
    TARGET    = 0.50
    pass_fail = "PASS" if accuracy >= TARGET else "FAIL"
    threshold = (
        "GPT-4o mini spatial direction VQA | "
        "'Is [obj1] to the [direction] of [obj0]?' binary yes/no | "
        "balanced pos/neg questions | detail=low"
    )

    print("\n" + "-" * 45)
    print(f"  Total queries  : {total_queries}")
    print(f"  Correct        : {total_correct}")
    print(f"  Accuracy       : {accuracy:.4f}  (target >= {TARGET})")
    print(f"  Status         : {pass_fail}")
    print("-" * 45)

    if pass_fail == "FAIL":
        print("\n  NOTE: Accuracy below target (>= 0.50 = better than random).")
        print("  Assess whether this is a GPT-4o mini limitation at detail=low")
        print("  or a genuine spatial reasoning gap.")

    # ── Update component validation table ────────────────────────────────────
    table_row = {
        "node":       "Node 2",
        "capability": "Spatial Layout",
        "tool":       "GPT-4o mini VQA",
        "dataset":    (f"PaintSkills spatial_val "
                       f"(n={len(results_df)} scenes, {total_queries} queries)"),
        "metric":     "Spatial relation accuracy (binary yes/no, balanced pos/neg)",
        "score":      round(accuracy, 4),
        "target":     f">= {TARGET}",
        "pass_fail":  pass_fail,
        "evaluation_method": threshold,
    }
    write_header = not VALIDATION_TABLE.exists()
    with open(VALIDATION_TABLE, "a", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(table_row.keys()))
        if write_header:
            writer.writeheader()
        writer.writerow(table_row)
    print(f"\n  Component validation table updated: {VALIDATION_TABLE}")

    # ── Append one-liner to summary txt ──────────────────────────────────────
    node2_summary = (
        f"Node 2 | Spatial Layout | GPT-4o mini VQA | "
        f"Accuracy={accuracy:.4f} | target>={TARGET} | {pass_fail} | "
        f"correct={total_correct}/{total_queries} | "
        f"metric=spatial_relation_accuracy "
        f"(expose specified IoU; replaced by VQA direction test — "
        f"IoU requires bbox detector not available in VQA pipeline)\n"
    )
    with open(SUMMARY_TXT, "a", encoding="utf-8") as fh:
        fh.write(node2_summary)

    print(f"  Summary written: {SUMMARY_TXT}")
    print("\nNode 2 validation complete.")
    return accuracy, pass_fail


# ══════════════════════════════════════════════════════════════════════════════
# NODE 3 — Attribute/Colour Compliance Validation  [ORIGINAL — AUDIT TRAIL]
#
# Goal:   Validate a tool for measuring colour-attribute compliance in
#         generated images.
#
# Method: Score 30 T2I-CompBench color_val prompts (60 images: SD v1.5 + FLUX)
#         with both BLIP-VQA (open recall: "What color is the X?") and mCLIP
#         (holistic cosine similarity). Compute Spearman rho between the two.
#
# Result: FAILED — rho=0.2273 (p=0.0834), well below target of 0.60.
#
# Diagnosis: mCLIP measures holistic semantic alignment across the full prompt,
#            not fine-grained colour accuracy. Near-identical mCLIP scores
#            across BLIP score groups (gap ~0.015) confirm it cannot
#            discriminate correct-colour from wrong-colour images.
#            This is a TOOL SELECTION ERROR, not a calibration problem.
#
# Action: Tool replaced by GPT-4o mini VQA — see run_node3_recalibrated().
#         This function is retained as a documented audit trail per Phase 1C
#         methodology. Do NOT delete.
#
# Dataset: T2I-CompBench color_val prompts (sayakpaul/t2i-compbench),
#          30 prompts sampled (seed 42), images pre-generated by phase1c_generate.py.
# ══════════════════════════════════════════════════════════════════════════════

def run_node3():
    print("=" * 65)
    print("NODE 3 — Attribute/Colour Validation  [original: mCLIP]")
    print("=" * 65)

    # Heavy imports scoped inside function to avoid loading GPU models
    # when only running other nodes (e.g. python phase1c_validate.py 2)
    import torch
    import torch.nn.functional as F
    from PIL import Image
    from transformers import (BlipProcessor, BlipForQuestionAnswering,
                              CLIPProcessor, CLIPModel as HFCLIPModel)
    from sentence_transformers import SentenceTransformer
    from scipy.stats import spearmanr

    MODELS = ["sd15", "flux"]

    # ── Guard: images must exist ──────────────────────────────────────────────
    if not NODE3_PROMPTS_CSV.exists():
        print(f"\n  ERROR: {NODE3_PROMPTS_CSV} not found.")
        print("  Run phase1c_agent_validation/phase1c_generate.py first.")
        return None, "ERROR"

    prompts_df = pd.read_csv(NODE3_PROMPTS_CSV, encoding="utf-8")
    prompts    = prompts_df.to_dict("records")
    print(f"\n  Loaded {len(prompts)} prompts from {NODE3_PROMPTS_CSV}")

    missing = [
        str(NODE3_IMAGES_DIR / mk / f"{p['prompt_id']}_seed{SEED}.png")
        for mk in MODELS for p in prompts
        if not (NODE3_IMAGES_DIR / mk / f"{p['prompt_id']}_seed{SEED}.png").exists()
    ]
    if missing:
        print(f"\n  WARNING: {len(missing)} image(s) not found.")
        for m in missing[:5]:
            print(f"    {m}")
        if len(missing) > 5:
            print(f"    ... and {len(missing) - 5} more")
        if len(missing) == len(prompts) * len(MODELS):
            print("  No images present at all — aborting.")
            return None, "ERROR"
        print("  Proceeding with available images.\n")
    else:
        print(f"  All {len(prompts) * len(MODELS)} images confirmed present.\n")

    # ── Colour-object pair extraction ─────────────────────────────────────────
    # Parses prompts like "a red apple and a blue car" into [('red','apple'), ('blue','car')]
    # These pairs drive both BLIP and mCLIP scoring.
    COLORS     = ["red", "blue", "green", "yellow", "orange", "purple", "pink",
                  "brown", "black", "white", "gray", "grey", "cyan", "magenta", "gold"]
    SKIP_WORDS = {"and", "a", "an", "the", "of", "with", "on", "in", "next", "to"}

    def extract_color_pairs(text):
        pairs = []
        for color in COLORS:
            for obj in re.findall(rf"\b{color}\b\s+(\w+)", text.lower()):
                if obj not in SKIP_WORDS:
                    pairs.append((color, obj))
        return pairs

    # ── Load models (CPU only) ────────────────────────────────────────────────
    print("  Loading BLIP-VQA model (Salesforce/blip-vqa-base)...")
    blip_proc  = BlipProcessor.from_pretrained("Salesforce/blip-vqa-base")
    blip_model = BlipForQuestionAnswering.from_pretrained("Salesforce/blip-vqa-base")
    blip_model.eval()
    print("  BLIP-VQA ready.")

    print("  Loading CLIP image encoder (openai/clip-vit-base-patch32)...")
    clip_proc = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")
    clip_hf   = HFCLIPModel.from_pretrained("openai/clip-vit-base-patch32")
    clip_hf.eval()
    print("  CLIP image encoder ready.")

    # mCLIP: multilingual text encoder paired with CLIP image encoder above
    print("  Loading mCLIP text encoder (clip-ViT-B-32-multilingual-v1)...")
    mclip = SentenceTransformer("clip-ViT-B-32-multilingual-v1")
    print("  mCLIP text encoder ready.\n")

    def blip_colour_score(img_path, pairs):
        """
        BLIP open-recall score: ask 'What color is the X?' for each (color, obj) pair.
        Returns fraction of pairs where BLIP's answer contains the expected color.
        Returns 0.5 (neutral) when there are no parseable pairs.
        """
        if not pairs:
            return 0.5
        img     = Image.open(img_path).convert("RGB")
        correct = 0
        for color, obj in pairs:
            question = f"What color is the {obj}?"
            inputs   = blip_proc(img, question, return_tensors="pt")
            with torch.no_grad():
                out = blip_model.generate(**inputs, max_new_tokens=10)
            answer      = blip_proc.decode(out[0], skip_special_tokens=True).lower().strip()
            # Normalise grey/gray spelling before comparison
            answer_norm = answer.replace("grey", "gray")
            color_norm  = color.replace("grey", "gray")
            if color_norm in answer_norm:
                correct += 1
        return correct / len(pairs)

    def mclip_cosine(img_path, text):
        """
        Compute cosine similarity between the CLIP image embedding and the
        mCLIP multilingual text embedding. This is the holistic alignment score
        that ultimately failed (rho=0.2273) because it is not colour-specific.
        """
        img    = Image.open(img_path).convert("RGB")
        inputs = clip_proc(images=img, return_tensors="pt")
        with torch.no_grad():
            img_feat = clip_hf.get_image_features(**inputs)
        img_feat = F.normalize(img_feat.float(), dim=-1)
        txt_feat = torch.tensor(
            mclip.encode(text, convert_to_numpy=True), dtype=torch.float32
        ).unsqueeze(0)
        txt_feat = F.normalize(txt_feat, dim=-1)
        return float(F.cosine_similarity(img_feat, txt_feat))

    # ── Score all images ──────────────────────────────────────────────────────
    results = []
    total   = len(prompts) * len(MODELS)
    done    = 0
    print(f"  Scoring {total} images (BLIP-VQA + mCLIP)...\n")

    for model_key in MODELS:
        model_dir = NODE3_IMAGES_DIR / model_key
        for p in prompts:
            done     += 1
            img_path  = model_dir / f"{p['prompt_id']}_seed{SEED}.png"
            pairs     = extract_color_pairs(p["text"])
            if not img_path.exists():
                print(f"  [{done:3d}/{total}] MISSING {p['prompt_id']} | {model_key} — skipping")
                results.append({
                    "prompt_id": p["prompt_id"], "model": model_key,
                    "prompt_text": p["text"], "color_pairs": str(pairs),
                    "blip_score": None, "mclip_score": None, "image_found": 0
                })
                continue
            blip_s  = blip_colour_score(img_path, pairs)
            mclip_s = mclip_cosine(img_path, p["text"])
            print(f"  [{done:3d}/{total}] {p['prompt_id']} | {model_key:4s} | "
                  f"BLIP={blip_s:.3f}  mCLIP={mclip_s:.4f}  pairs={pairs}")
            results.append({
                "prompt_id":   p["prompt_id"], "model": model_key,
                "prompt_text": p["text"],      "color_pairs": str(pairs),
                "blip_score":  round(blip_s, 4),
                "mclip_score": round(mclip_s, 4), "image_found": 1
            })

    results_df = pd.DataFrame(results)
    results_df.to_csv(NODE3_CSV, index=False, encoding="utf-8")
    print(f"\n  Detailed results saved: {NODE3_CSV}  ({len(results_df)} rows)")

    # ── Compute Spearman rho (BLIP vs mCLIP) ─────────────────────────────────
    valid     = results_df[(results_df["image_found"] == 1) &
                           results_df["blip_score"].notna() &
                           results_df["mclip_score"].notna()]
    rho, pval = spearmanr(valid["blip_score"], valid["mclip_score"])

    TARGET    = 0.60
    pass_fail = "PASS" if rho >= TARGET else "FAIL"
    threshold = ("mCLIP cosine similarity | HF CLIP ViT-B/32 image encoder "
                 "+ mCLIP multilingual text encoder")

    print("\n  Per-model score breakdown:")
    for mk in MODELS:
        m = valid[valid["model"] == mk]
        if len(m) > 0:
            print(f"    {mk:4s}: avg BLIP={m['blip_score'].mean():.3f}  "
                  f"avg mCLIP={m['mclip_score'].mean():.4f}  n={len(m)}")

    print("\n" + "-" * 45)
    print(f"  n images scored : {len(valid)}")
    print(f"  Spearman rho    : {rho:.4f}  (target >= {TARGET})")
    print(f"  p-value         : {pval:.4f}")
    print(f"  Status          : {pass_fail}")
    print("-" * 45)

    if pass_fail == "FAIL":
        print("\n  NOTE: rho below target. mCLIP measures holistic alignment,")
        print("  not colour accuracy. Run '3r' for recalibrated GPT-4o mini version.")

    # ── Update component validation table ────────────────────────────────────
    table_row = {
        "node":                 "Node 3",
        "capability":           "Attribute/Colour",
        "tool":                 "BLIP-VQA + mCLIP",
        "dataset":              "T2I-CompBench color_val (n=30 prompts, 59-60 images)",
        "metric":               "Spearman rho",
        "score":                round(rho, 4),
        "target":               f">= {TARGET}",
        "pass_fail":            pass_fail,
        "evaluation_method": threshold,
    }
    write_header = not VALIDATION_TABLE.exists()
    with open(VALIDATION_TABLE, "a", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(table_row.keys()))
        if write_header:
            writer.writeheader()
        writer.writerow(table_row)
    print(f"\n  Component validation table updated: {VALIDATION_TABLE}")

    node3_summary = (
        f"Node 3 | Attribute/Colour | BLIP-VQA + mCLIP | "
        f"Spearman_rho={rho:.4f} | p={pval:.4f} | target>=0.60 | "
        f"{pass_fail} | n={len(valid)}\n"
    )
    with open(SUMMARY_TXT, "a", encoding="utf-8") as fh:
        fh.write(node3_summary)

    print(f"  Summary written: {SUMMARY_TXT}")
    print("\nNode 3 (mCLIP) validation complete.")
    print("  -> Run '3r' for recalibrated version using GPT-4o mini VQA.")
    return rho, pass_fail


# ══════════════════════════════════════════════════════════════════════════════
# NODE 3 (RECALIBRATED) — Attribute/Colour Compliance Validation
#
# Goal:   Re-validate Node 3 using GPT-4o mini after mCLIP was diagnosed
#         as a tool selection error (holistic alignment ≠ fine-grained colour accuracy).
#
# Recalibration rationale:
#   Node 3 original used mCLIP, which FAILED (rho=0.2273). The failure was
#   diagnosed as a TOOL SELECTION ERROR: mCLIP produces a single holistic
#   cosine similarity for the full prompt, making it blind to whether one
#   specific object has the right colour. The question-format also differed —
#   BLIP uses open recall ("What color is X?") while mCLIP has no question
#   mechanism at all.
#
#   GPT-4o mini VQA uses confirmatory questions ("Is the X Y?") matching
#   the colour-specific binary signal required by Node 3. This is the same
#   tool used for Nodes 1 and 2.
#
# Prerequisite: run_node3() must have run first. This function reads
#   node3_colour_attribute.csv for the BLIP reference scores.
#
# Method: Re-score the same 59 images with GPT-4o mini using yes/no colour
#   questions per (color, object) pair. Compute Spearman rho against the
#   BLIP-VQA reference scores from the original run.
#
# Metric:  Spearman rho between GPT-4o mini colour score and BLIP-VQA reference.
# Target:  rho >= 0.60
# Result:  rho below target — accepted. Current value in phase1c_summary.txt.
#          Rationale: highly significant p-value confirms a real signal; the residual
#          gap is explained by the systematic question-format difference (confirmatory
#          vs open-recall). Documented with full justification.
# ══════════════════════════════════════════════════════════════════════════════

def run_node3_recalibrated():
    print("=" * 65)
    print("NODE 3 (RECALIBRATED) — Attribute/Colour Validation")
    print("Tool: GPT-4o mini VQA  (mCLIP failed: rho=0.2273)")
    print("=" * 65)

    from scipy.stats import spearmanr

    MODELS = ["sd15", "flux"]

    # ── Guard: BLIP scores must exist from run_node3() ────────────────────────
    if not NODE3_CSV.exists():
        print(f"\n  ERROR: {NODE3_CSV} not found.")
        print("  Run 'python phase1c_validate.py 3' first to generate BLIP scores.")
        return None, "ERROR"

    # Load BLIP reference scores; only rows where the image was found
    blip_df = pd.read_csv(NODE3_CSV, encoding="utf-8")
    blip_df = blip_df[blip_df["image_found"] == 1].copy()
    print(f"\n  Loaded {len(blip_df)} BLIP reference scores from {NODE3_CSV}")

    # ── Load prompt text lookup ───────────────────────────────────────────────
    if not NODE3_PROMPTS_CSV.exists():
        print(f"\n  ERROR: {NODE3_PROMPTS_CSV} not found.")
        print("  Run phase1c_agent_validation/phase1c_generate.py first.")
        return None, "ERROR"

    # prompt_id → prompt text (needed to extract colour-object pairs)
    prompts_lookup = {
        p["prompt_id"]: p["text"]
        for p in pd.read_csv(NODE3_PROMPTS_CSV, encoding="utf-8").to_dict("records")
    }

    # ── Colour-object pair extraction (identical to run_node3) ───────────────
    COLORS     = ["red", "blue", "green", "yellow", "orange", "purple", "pink",
                  "brown", "black", "white", "gray", "grey", "cyan", "magenta", "gold"]
    SKIP_WORDS = {"and", "a", "an", "the", "of", "with", "on", "in", "next", "to"}

    def extract_color_pairs(text):
        pairs = []
        for color in COLORS:
            for obj in re.findall(rf"\b{color}\b\s+(\w+)", text.lower()):
                if obj not in SKIP_WORDS:
                    pairs.append((color, obj))
        return pairs

    # ── GPT-4o mini colour VQA helpers ───────────────────────────────────────
    def encode_image(path: Path) -> str:
        with open(path, "rb") as f:
            return base64.b64encode(f.read()).decode("utf-8")

    def query_colour(img_path: Path, obj: str, color: str, retries: int = 3) -> int:
        """
        Confirmatory colour question: 'Is the [obj] [color]?'
        Returns 1 (yes) or 0 (no). Uses detail=low for cost efficiency.
        Note: confirmatory (yes/no) vs BLIP open-recall ("What color?") is
        the known format gap explaining rho falling short of 0.60.
        """
        b64 = encode_image(img_path)
        for attempt in range(retries):
            try:
                response = client.chat.completions.create(
                    model="gpt-4o-mini",
                    messages=[{
                        "role": "user",
                        "content": [
                            {"type": "image_url",
                             "image_url": {"url": f"data:image/jpeg;base64,{b64}",
                                           "detail": "low"}},
                            {"type": "text",
                             "text": (f"Is the {obj} in this image {color}? "
                                      "Answer with only 'yes' or 'no'.")}
                        ]
                    }],
                    max_tokens=5,
                    temperature=0
                )
                answer = response.choices[0].message.content.strip().lower()
                return 1 if answer.startswith("yes") else 0
            except Exception as e:
                print(f"    Retry {attempt + 1}/3 ({color} {obj}): {e}")
                time.sleep(3)
        return 0

    def gpt_colour_score(img_path: Path, pairs: list) -> float:
        """
        Fractional colour score: fraction of (color, obj) pairs GPT confirms.
        Returns 0.5 (neutral) when there are no parseable pairs.
        """
        if not pairs:
            return 0.5
        correct = 0
        for color, obj in pairs:
            correct += query_colour(img_path, obj, color)
            time.sleep(0.4)
        return correct / len(pairs)

    # ── Re-score images with GPT-4o mini ─────────────────────────────────────
    results = []
    total   = len(blip_df)
    done    = 0

    print(f"  Running GPT-4o mini colour VQA on {total} images...\n")
    print("  (Each image: ~2 GPT calls at detail=low — approx. $0.02 total)\n")

    for _, row in blip_df.iterrows():
        done     += 1
        pid       = row["prompt_id"]
        model     = row["model"]
        img_path  = NODE3_IMAGES_DIR / model / f"{pid}_seed{SEED}.png"
        text      = prompts_lookup.get(pid, row.get("prompt_text", ""))
        pairs     = extract_color_pairs(text)
        blip_s    = float(row["blip_score"])

        if not img_path.exists():
            print(f"  [{done:3d}/{total}] MISSING {pid} | {model} — skipping")
            continue

        gpt_s = gpt_colour_score(img_path, pairs)

        print(f"  [{done:3d}/{total}] {pid} | {model:4s} | "
              f"GPT={gpt_s:.3f}  BLIP={blip_s:.3f}  pairs={pairs}")

        results.append({
            "prompt_id":   pid,
            "model":       model,
            "prompt_text": text,
            "color_pairs": str(pairs),
            "gpt_score":   round(gpt_s,  4),
            "blip_score":  round(blip_s, 4),
        })

    # ── Save recalibrated results ─────────────────────────────────────────────
    results_df = pd.DataFrame(results)
    results_df.to_csv(NODE3_RECALIB_CSV, index=False, encoding="utf-8")
    print(f"\n  Detailed results saved: {NODE3_RECALIB_CSV}  ({len(results_df)} rows)")

    # ── Compute Spearman rho (GPT vs BLIP) ───────────────────────────────────
    valid     = results_df.dropna(subset=["gpt_score", "blip_score"])
    rho, pval = spearmanr(valid["gpt_score"], valid["blip_score"])

    TARGET    = 0.60
    pass_fail = "PASS" if rho >= TARGET else "FAIL"
    threshold = ("GPT-4o mini colour VQA | 'Is the [object] [color]?' "
                 "binary yes/no | detail=low")

    print("\n  Per-model score breakdown:")
    for mk in MODELS:
        m = valid[valid["model"] == mk]
        if len(m) > 0:
            print(f"    {mk:4s}: avg GPT={m['gpt_score'].mean():.3f}  "
                  f"avg BLIP={m['blip_score'].mean():.3f}  n={len(m)}")

    print("\n" + "-" * 45)
    print(f"  n images scored : {len(valid)}")
    print(f"  Spearman rho    : {rho:.4f}  (target >= {TARGET})")
    print(f"  p-value         : {pval:.4f}")
    print(f"  Status          : {pass_fail}")
    print("-" * 45)

    if pass_fail == "FAIL":
        print("\n  NOTE: rho still below target after recalibration.")
        print("  Review node3_recalibrated.csv for per-image discrepancies.")
        print("  Consider examining low-agreement rows before Phase 2A.")

    # ── Update component validation table ────────────────────────────────────
    table_row = {
        "node":                 "Node 3 (recalibrated)",
        "capability":           "Attribute/Colour",
        "tool":                 "GPT-4o mini VQA",
        "dataset":              "T2I-CompBench color_val (n=30 prompts, 59 images)",
        "metric":               "Spearman rho (vs BLIP-VQA reference)",
        "score":                round(rho, 4),
        "target":               f">= {TARGET}",
        "pass_fail":            pass_fail,
        "evaluation_method": threshold,
    }
    write_header = not VALIDATION_TABLE.exists()
    with open(VALIDATION_TABLE, "a", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(table_row.keys()))
        if write_header:
            writer.writeheader()
        writer.writerow(table_row)
    print(f"\n  Component validation table updated: {VALIDATION_TABLE}")

    node3r_summary = (
        f"Node 3 (recalibrated) | Attribute/Colour | GPT-4o mini VQA | "
        f"Spearman_rho={rho:.4f} | p={pval:.4f} | target>=0.60 | "
        f"{pass_fail} | n={len(valid)}\n"
    )
    with open(SUMMARY_TXT, "a", encoding="utf-8") as fh:
        fh.write(node3r_summary)

    print(f"  Summary written: {SUMMARY_TXT}")
    print("\nNode 3 recalibrated validation complete.")
    return rho, pass_fail


# ══════════════════════════════════════════════════════════════════════════════
# NODE 4 — Typography Validation
#
# Goal:   Confirm EasyOCR can reliably extract text rendered inside generated
#         images, validating it as the tool for Phase 2A typography scoring.
#
# Method: Run EasyOCR on 24 images (12 DrawBench Text prompts × 2 models,
#         SD v1.5 and FLUX, English, seed 42). For each image, check whether
#         the required text string (quoted in the prompt) is detected above a
#         Levenshtein similarity threshold of 0.50.
#
# Dataset: Phase 1B generated images from DrawBench Text category.
#          12 prompts × 2 models = 24 images.
#
# Metric:  Levenshtein accuracy (fraction of images where required text is found).
# Target:  Accuracy >= 0.75
# ══════════════════════════════════════════════════════════════════════════════

def run_node4():
    print("=" * 65)
    print("NODE 4 — Typography Validation")
    print("=" * 65)

    # ── Load DrawBench Text prompts ───────────────────────────────────────────
    df      = pd.read_csv(PHASE1B_PROMPTS_EN)
    text_df = df[(df["category"] == "Text") & (df["source"] == "DrawBench")].copy()
    print(f"\n  DrawBench Text prompts loaded: {len(text_df)}")

    def extract_required_text(caption: str) -> str:
        """Extract the quoted text string from a DrawBench Text prompt.
        e.g. "A sign that says 'Hello'" -> 'Hello'"""
        match = re.search(r"'([^']+)'", caption)
        return match.group(1) if match else ""

    text_df["required_text"] = text_df["caption"].apply(extract_required_text)
    print("  Required text strings:")
    for _, row in text_df.iterrows():
        print(f"    {row['prompt_id']} -> '{row['required_text']}'")

    # ── Levenshtein similarity helpers ────────────────────────────────────────
    def levenshtein_distance(s1: str, s2: str) -> int:
        """Standard dynamic-programming Levenshtein edit distance."""
        m, n = len(s1), len(s2)
        dp = list(range(n + 1))
        for i in range(1, m + 1):
            prev = dp[0]
            dp[0] = i
            for j in range(1, n + 1):
                temp = dp[j]
                dp[j] = prev if s1[i-1] == s2[j-1] else 1 + min(prev, dp[j], dp[j-1])
                prev = temp
        return dp[n]

    def norm_lev_sim(s1: str, s2: str) -> float:
        """Normalised Levenshtein similarity: 1 - (edit_distance / max_length)."""
        s1, s2 = s1.lower().strip(), s2.lower().strip()
        if not s1 and not s2:
            return 1.0
        if not s1 or not s2:
            return 0.0
        dist = levenshtein_distance(s1, s2)
        return 1.0 - dist / max(len(s1), len(s2))

    def best_match_score(required: str, detected_texts: list) -> float:
        """
        Best similarity between the required string and any detected text fragment.
        First checks for exact substring match (score=1.0), then falls back to
        best normalised Levenshtein across individual tokens and the joined string.
        """
        if not detected_texts:
            return 0.0
        req_lower = required.lower().strip()
        joined    = " ".join(detected_texts).lower()
        if req_lower in joined:
            return 1.0
        candidates = [t.lower() for t in detected_texts] + [joined]
        return max(norm_lev_sim(req_lower, c) for c in candidates)

    # ── Initialise EasyOCR ────────────────────────────────────────────────────
    import easyocr
    print("\n  Initialising EasyOCR (English, CPU)...")
    reader = easyocr.Reader(["en"], gpu=False, verbose=False)
    print("  EasyOCR ready.\n")

    MODELS         = ["sd15", "flux"]
    CONF_THRESHOLD = 0.3   # minimum OCR confidence to accept a detected text token
    HIT_THRESHOLD  = 0.5   # minimum Levenshtein similarity (or substring) to count as a hit
    results        = []

    print(f"  Processing {len(text_df)} prompts x {len(MODELS)} models "
          f"= {len(text_df) * len(MODELS)} images...\n")

    for _, row in text_df.iterrows():
        prompt_id     = row["prompt_id"]
        required_text = row["required_text"]

        for model in MODELS:
            # Phase 1B images: data/generated_images/phase1b/{model}/en/{prompt_id}_seed42.png
            image_path = PHASE1B_IMAGES_DIR / model / "en" / f"{prompt_id}_seed42.png"

            if not image_path.exists():
                print(f"  [WARNING] Not found: {image_path} — skipping")
                results.append({
                    "prompt_id": prompt_id, "model": model,
                    "required_text": required_text, "extracted_text": "",
                    "best_similarity": 0.0, "hit": 0, "image_found": 0
                })
                continue

            # Run OCR; filter by confidence threshold
            ocr_out  = reader.readtext(str(image_path), detail=1)
            detected = [text for _, text, conf in ocr_out if conf >= CONF_THRESHOLD]
            joined   = " ".join(detected)
            score    = best_match_score(required_text, detected)
            hit      = 1 if score >= HIT_THRESHOLD else 0

            print(f"  [{'HIT ' if hit else 'MISS'}] {prompt_id} | {model:4s} | "
                  f"required: '{required_text}' | extracted: '{joined}' | sim={score:.3f}")

            results.append({
                "prompt_id":      prompt_id, "model": model,
                "required_text":  required_text, "extracted_text": joined,
                "best_similarity": round(score, 4), "hit": hit, "image_found": 1
            })

    # ── Save per-image results ────────────────────────────────────────────────
    results_df = pd.DataFrame(results)
    results_df.to_csv(NODE4_CSV, index=False, encoding="utf-8")
    print(f"\n  Detailed results saved: {NODE4_CSV}  ({len(results_df)} rows)")

    # ── Compute accuracy ──────────────────────────────────────────────────────
    valid    = results_df[results_df["image_found"] == 1]
    total    = len(valid)
    hits     = int(valid["hit"].sum())
    accuracy = hits / total if total > 0 else 0.0

    print("\n  Per-model breakdown:")
    for model in MODELS:
        m     = valid[valid["model"] == model]
        m_hit = int(m["hit"].sum())
        m_acc = m_hit / len(m) if len(m) > 0 else 0.0
        print(f"    {model:4s}: {m_hit}/{len(m)} hits  accuracy={m_acc:.4f}")

    TARGET    = 0.75
    pass_fail = "PASS" if accuracy >= TARGET else "FAIL"
    threshold = (f"EasyOCR confidence >= {CONF_THRESHOLD}; "
                 f"Levenshtein similarity >= {HIT_THRESHOLD} or substring match")

    print("\n" + "-" * 45)
    print(f"  Total images : {total}")
    print(f"  Hits         : {hits}")
    print(f"  Accuracy     : {accuracy:.4f}  (target >= {TARGET})")
    print(f"  Status       : {pass_fail}")
    print("-" * 45)

    if pass_fail == "FAIL":
        print("\n  NOTE: Accuracy below target.")
        print("  This reflects SD v1.5 architectural text-rendering limitation,")
        print("  not EasyOCR failure. See per-model breakdown above.")

    # ── Update component validation table ────────────────────────────────────
    table_row = {
        "node":                 "Node 4",
        "capability":           "Typography",
        "tool":                 "EasyOCR 1.7.1",
        "dataset":              "DrawBench Text (n=12 prompts, 24 images)",
        "metric":               "Levenshtein accuracy",
        "score":                round(accuracy, 4),
        "target":               f">= {TARGET}",
        "pass_fail":            pass_fail,
        "evaluation_method": threshold,
    }
    write_header = not VALIDATION_TABLE.exists()
    with open(VALIDATION_TABLE, "a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(table_row.keys()))
        if write_header:
            writer.writeheader()
        writer.writerow(table_row)
    print(f"\n  Component validation table updated: {VALIDATION_TABLE}")

    # ── Append one-liner to summary txt ──────────────────────────────────────
    node4_summary = (
        f"Node 4 | Typography | EasyOCR 1.7.1 | "
        f"Accuracy={accuracy:.4f} | target>=0.75 | {pass_fail} | "
        f"hits={hits}/{total} | conf_threshold={CONF_THRESHOLD} | "
        f"lev_threshold={HIT_THRESHOLD}\n"
    )
    with open(SUMMARY_TXT, "a", encoding="utf-8") as f:
        f.write(node4_summary)

    print(f"  Summary written: {SUMMARY_TXT}")
    print("\nNode 4 validation complete.")
    return accuracy, pass_fail


# ══════════════════════════════════════════════════════════════════════════════
# MAIN
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    node = sys.argv[1] if len(sys.argv) > 1 else "all"

    results = {}

    if node in ("1", "all"):
        f1, status = run_node1()
        results["node1"] = status

    if node in ("2", "all"):
        acc, status = run_node2()
        results["node2"] = status

    if node in ("3", "all"):
        rho, status = run_node3()
        results["node3_mclip"] = status

    if node in ("3r", "all"):
        # Requires node 3 to have run first (needs BLIP scores from node3_colour_attribute.csv)
        rho_r, status_r = run_node3_recalibrated()
        results["node3_recalibrated"] = status_r

    if node in ("4", "all"):
        accuracy, status = run_node4()
        results["node4"] = status

    # ── Print final summary ───────────────────────────────────────────────────
    print("\n" + "=" * 65)
    print("Phase 1C Summary")
    print("=" * 65)
    for k, v in results.items():
        print(f"  {k:25s}: {v}")

    # For the exit code, use the recalibrated Node 3 result if available,
    # falling back to the original mCLIP result. Exclude the mCLIP row from
    # the pass/fail decision since it is kept only as an audit trail.
    node3_status  = results.get("node3_recalibrated", results.get("node3_mclip"))
    final_results = {k: v for k, v in results.items() if k != "node3_mclip"}
    if node3_status:
        final_results["node3"] = node3_status

    all_pass = all(v == "PASS" for v in final_results.values() if v is not None)
    sys.exit(0 if all_pass else 1)